name: ftest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '10'
      - name: Setup k3s
        run: |
          curl -sfL https://get.k3s.io | sh -s - --write-kubeconfig-mode 644
          mkdir ~/.kube && cp /etc/rancher/k3s/k3s.yaml ~/.kube/config
      - name: Start Nuxeo
        env:
          NUXEO_CLID: ${{ secrets.clid }}
        run: ./start_nuxeo.sh
      - name: Functional Tests
        run: ./run_ftest.sh

