name: ftest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '10'
      - uses: nelsonsilva/setup-k3s@v0.1.0
      - name: Start Nuxeo
        env:
          NUXEO_CLID: ${{ secrets.clid }}
        run: ./start_nuxeo.sh
      - name: Functional Tests
        run: ./run_ftest.sh

